title: The MICYCLE Study 
description: Explore the MICYCLE Study, a research project investigating how the vaginal microbiome changes throughout the menstrual cycle in response to various factors such as diet, mood, stress, sex, and exercise. Participants gain insights into their menstrual health through access to an at-home urine analyzer and a cycle tracking application. Join us in advancing scientific knowledge while learning more about your own menstrual cycle.
theme: minima
markdown: kramdown
